# Generated by Django 4.0 on 2021-12-28 19:42

from django.db import migrations

from main.constants import FILM_LIST_TYPES


def create_films_list(apps, schema_editor):
    User = apps.get_model("main", "CustomUser")
    FilmsList = apps.get_model("main", "FilmsList")
    for user in User.objects.all():
        for list_type in FILM_LIST_TYPES:
            if not FilmsList.objects.filter(type=list_type[0], user=user).exists():
                FilmsList.objects.create(type=list_type[0], user=user)


def delete_films_list(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_film_genre'),
    ]

    operations = [
        migrations.RunPython(create_films_list, delete_films_list),
    ]
