# Generated by Django 4.0 on 2022-01-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211228_2142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmslist',
            unique_together={('user', 'type')},
        ),
    ]
