# Generated by Django 4.0 on 2022-01-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_filmslist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmslist',
            name='film',
            field=models.ManyToManyField(blank=True, related_name='films_lists', to='main.Film'),
        ),
    ]
